services:
  simple-apps:
    container_name: ct-simpleapps
    build: /app
    ports:
      - "8181:3000"
    env_file:
      - DB_NAME=training
      - DB_HOST=172.23.9.35
      - DB_USER=peserta
      - DB_PASSWORD=password
      - APP_PORT=3000
    restart: always